
#server \uC124\uC815
server.port = 8100

#sql log\uC124\uC815
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/tp
spring.datasource.username=root
spring.datasource.password=dev0523

spring.datasource.driverClassName=net.sf.log4jdbc.sql.jdbcapi.DriverSpy


#thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.check-template-location=true
#\uD15C\uD50C\uB9BF HTML\uC774 \uD3EC\uD568\uB41C URL
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

#mybatis
mybatis.type-aliases-package=com.UserRole.mapper 
mybatis.mapper-locations:classpath:mapper/*.xml

# thymeleaf html/css \uBC14\uB85C \uC801\uC6A9\uD558\uAE30
#\uC808\uB300\uACBD\uB85C C:\Users\Basic international\IdeaProjects\UserRole
project.base-dir=file:////Users/Basic international/IdeaProjects/UserRole

#\uC815\uC801\uD30C\uC77C(javascript.css\uB4F1\uB4F1) \uC704\uCE58
spring.web.resources.static-locations=${project.base-dir}/src/main/resources/static/




